Repository dwyl/process-handbook, pull requests merged in 2018-10, with the labels that each got.

#117 #115 Creates personas readme
  how-to-create-personas.md
Labels: awaiting-review

#118 Update expenses policy
  finances.md
Labels: in-review

#119 Clarifies NICs allowance
  finances.md
Labels: awaiting-review

#121 Keeps payroll separate from freelancers
  finances.md
Labels: awaiting-review, priority-4

#122 Create README for running reports
  reports.md
Labels: awaiting-review, priority-4

#124 Adds process for payroll reports
  reports.md
Labels: awaiting-review, priority-4

#127 Coop banking feed into Xero
  Finances/Banking-feeds.md
  Finances/incoming-invoices.md
Labels: awaiting-review

#129 Santander feed update
  Finances/Banking-feeds.md
Labels: T25m, awaiting-review, priority-4
